language: java
sudo: false

jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

install: true
script: ./travis.sh
env:
  - TESTS=CI
  - TESTS=IT-DEV

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
