language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - secure: "Q70fT8zGVpAtsiuaxQq8ah+o8cV7gMv5uEt3VRo97e2dqL9iv48wz9YiHQiWOLo0yWWs71iFQjEbvsgq2OnUdMM4sSFEdd9TcslVRkcxeJq2VeAZ267PioU353ewzW819cixavALEBYqpA2H/G9eeo4lGFZalapmdCD+n7ZdTj5LnUyM3/CLAC4bk9EL7mCpPUsMTWf2LOVdjCRdlYXm/3qp1ipMi0sX1wx1fGEjQWHTTTKpLQAjDeSSIFTNqhPoEV5UWcb4VmjVt4IaLyL6uAz2yg/TXD5mOWVcGAQLc+4TKykrpYblkqKsIbTldivNI8D72Pprwr25Rj8X+D3q3lmlH/1OJMTn0ZduoJY9cz55pS8i0/epzG3TmDRi9IB7Qer+hq4xBOvVv1JU3uqlc16NI42qZZ6cbhyxCM24V7m1LM5wuyDEDFdge/wgdAhzdNcxOGVcoAVi4cAU+emPRzwFBkDtaAtsmAEMuUdKNj/+9hpX15/U33aCZq8unFbR4w13JJrgjIOlb3DyIcz/LXsJxPZUI/unWai25LhmjTHqjCH2i95WHkJvhGLvH7aEoFYvxDk4+kTxHwxNq2j7JBWW8XbamcPJLnZYxOe2YkuwyLKkgVmAzfSZCp62sOgHwY3VfffhBz+uIWTBnJPEcU5QpBHKmdycVKiGmHO+DFw="
    - secure: "grkuwktq5XShP+dD99ZYmo5pg/mkBWLD9/l05lHhS121UUE6PiA3FAophlZNMfVXAjxgKEUAk0UeenmSA+H0WmClp3zEAxpv3wRPIaGT6UB1Sc8JbOLfuYjEkaFpljGHBv8b6wmgQwD55PDvou2Z2K/YsQSMKjhepNzt+nROSZqhWvH4IQknG+qSH05qMFW30X22inHShXJkvlFBc7Bqmej8PVuc1KHFp786aFf+7XpNytF6umnHQLXB8EGibhu80FBm87tikY6qOtl62nPRUtzY4a0ts1FEiWLtiXQKylroyEbl0VvJbewoxbzMvl9bayGpE0U6AwtwIFFad26g9c6hNmcCmac26OHFWtTVrkVddKvcfarrPUQYwCHu5bb26gbYAsZL7JX4mNoTNvVeAQC4PMYrNmxAhdVySM+VH8dCrrKHzm7U9n/YvPpeeh3ZhDc4uCd+EJAbpQJcY9qn5dFZjx3xHKUFPSpaCeo7U8DawzaUDXqafkbVxxTgpxxH0UEP4mufIs5SGSKlP3KMmYZoNbzh/h61U2vcHea1iE3Pyhsc+Tq5z0Q2cXPMaPj8gnYRxRMqii6b2eDrjcIk+EU5E9KOuKP3onpr8T/iOpU/r8lZXO+Rr0MFVso+bX3+NAsVJnrK02Et2FwmregIhNB19vOAkpnn9MKvTmfhEWM="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
