language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

env:
  global:
    - secure: "SLRo7/+3fSN3TWKdXiMQCijO6Pxv2OqvyBe6QHFymWB1iFHaujRIKl+I4hLvJg5HzXpsEYvlI8XaHGLrgGxzdOxrN9BY2SjZkJbfgkz2lNW+cl37qsXkPN50ARHkhjLTlUCN0SA/C5kcEsb8O+CaMvmz6Vd1lyW8wtxplHZuzJLmjiMLs7XKXXC+BLaINawila74im5JcFz/yE3f9Zf2g5kTy0KB1mVXT0gySMPu/u9OhxY2eXGLQNp10oHbnkVPfUcjpdpIlcepWxwDMc5Z0z/DW//b3uvOGlqAnKPztUmVvLgWth5MwxemBxnwgNPzEHkwMjqCi2DdTG4prno8gh3AfyS4+tNhFRQxfHbieXLHuLzOzPt60z3TopCWmvHPx1c/BoTZ6JpGg8zaF3nytubqWz1JoD84r1W+yRoRdOrMbVd61UIq9yFO1cO3AyKPHlZZ5d8DdheXJJ6tUlT+kh/rBL8kg0FPPj2pI6lrKyTVOAc9B0SbCXdqlZ2Q86dHiuN/yriicZRfRusgVBMqYn+zzzMuXxSCBDuGnEHET1sty6OZB+tvKpe9bJ+c/3sG3k/cpUhlOlds53Hob3HBgpulVMdE4PrlJ8uTviOLobXmoY5aI9VWDPjAjvVyG9sFNlxv9/lWs1gR3i/HxpOLYeQnUQwaN7m4+ULanohD5K4="
    - secure: "jYLEiSs7qLwyvVkcKFx/FS8PMK/qEnHYT185CuLti2/R011arBAAIjrFF0o4QmFUYLi1POAvfk5/W6UfaYPYUuutxUN/Vz9x793Eo0CEN2rcPETjei/+4S1LOJFWH3SQlFUQSudA1j1CbaWkzXpGZtj4xhpn/a+HwuvOFHPNDAcm2KjIkkE/fvPnB6wGFvF+AswuyrbRILy/NZtFgRcU5cFK2rPmooQmkPpetjrU87EvQGA+oic1KX5pnt5snGO2YMwhbQuFr8GR5aYlhqkz7ppHzydERmka9PX0ickdDTo8nJ4F7vUTqtCndU6GoR+sViNSB/M798qd87n/TyURxHrB8Zjtfj1v4ThAOfnKagHCR/l8WYsm1ODmgsMbU8+yyI5lBv5ZXsCH6VDWrTbo/bkxipfDqDEGtXpvvaQCRbjKXahTlZeswnCMNOo5y+zghir6wu9adpiRwAPaxYPE7DO7qBPqT2vyk6j1q1HH31MXdQW/vonb+rQPNrbsSFVmOC6G2fyYbkXi3VdiLr2ENg9g1p+JftE4wEcP+0kVotX6K/0sHvAyW8ADRtNufJJJDv+J6qfFKMyMIg2ghsWSdSlrBLnTi56Lt08QPlJkaJ4xuW2L1xxOO+z8mN8wUljLmsIK0tB09xwIZ2L/+LaKuISJR27tXRNlv67Ms9M+mOY="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
