dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "HJzMrBMjJ9+H1UroodSLo0tiUrBytZQz1EqGykWqU/PcgwVjVSTPqvLmFkfPbIZm3on9GElblUQqXV3/J9X2UTu4a/ZmWL5v09Tk2O12jKGbFV71LtlDFvvIoy8DtIIfnE0r642wyu6ii3VVt1J6FI/oixNmF25S6DdWDaA+q3NWlA+MZEae3n1YuQmhkpgoMkWe6xC3H6Oxdo0XgTn0SfqfBES8IM+3hG4FCU6tYfOVoffVEUd1eq3J9W7aGfMQ4zTEAorwroyWuFRDbG+W+PK8uMUJpSDDzjq3271yJAFPtLlGL2f+JPZO5GUui1IW+VM4Ju9YhQ5MiYzQXpdIUKFtBQZr480PrmTL9hP0zZFJA/QkBYr6otyBvaDOEkM1Bv/I9v2EjiutfVKVP09FKIEMNASdCCvtJ6p+BS3r2a74MZNcFtqcjXPd8ROxrh49n6hrkt99jvwsybgTpsgayTxT0N6Pdd1ni6sAiQ3LtXo6vFCi2apJ1v1hBoOXRfNvIdq00inyQI/P3LNcQzXLTou63oh2Z+I7UJcQHnl0pc4pndQMQm4A+22fFUrXRByPJK2dZpd7l/PSIEl0reirzk3UIUw1qmJlZyabAmPJPzPjvodjbH3pH5mK0S050UNDXi6G1u+F91td5gMrXxq3sA4/GIp1RpyoovSrOzIZEf4="
    - secure: "f2VyGgUMi0Y6rS+vhRJx2Ait1LQ0fJYAVsTyo9MVCRzkfbYbxTj9j92Z65iGeJDLqQcJ2D/9bSxUjMkMQeTFquSRvwMOPEVqp1ScwHex0rzOdXTwFgQEDldmi8TKJHkv+OK0hbOUQ2EwTUTGjXlo75pz1vq37nuTZUdxaE+9dHwI119wqKkldmH4rVVpebTIKlbY8iMkit8lRNFeg2RLTpNuYeovemZ33b6j51z1XvkGTzueqjdMEjydDQdwY6JrCi23bfe/V0dgnSc1WVjoPWLzAkGeGRGJTehrRBeAPK34GiiPfk+QL7srZY5MBsyi1ogCP3QRv70WziOxsgCfKHEU5kxmUCPUvoHbiFRwiPoOGvs7J/6GutqMwFqwNt6Fh1HI3euheXSixGQYr4fgrXI6UeRlbYdlQmUhRuvlp+q3JEo+Gcw6S3Ze/B0hQH3GrV30AMR7oYBAJElKXkoP3nX0d+z9YD9qlyvh2lju487ZFt1vCjgNa1KVT2uug4NLOiGFBn9Eanm1ubljesR5kvzGtXa8Vgtq2uAmPSRHYW8hCspnrUSk8A12M0QU3aErFF+FAjCxpoj5HvOVNtSTc9LHCr2HK124jzVrSVVZySeuqsnwb9taWdfNIcNOX/IJn00piven59CZWAvtmwjSuU5+3XfLsIhDiHXaMmNfpWs="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
